-- 📊 Basic KPI Analysis
-- What is the total revenue generated by the cafe?
SELECT 
	SUM(total_spent) AS total_revenue_generated
FROM clean_cafe_sales_data;
-- How many transactions were recorded?
SELECT 
	COUNT(transaction_id) AS total_transaction
FROM clean_cafe_sales_data;
-- What is the total quantity of items sold?
SELECT 
	SUM(quantity) AS total_sold_quantity
FROM clean_cafe_sales_data;
-- What is the average order value?
SELECT 
	ROUND(AVG(total_spent),2) AS average_order_value
FROM clean_cafe_sales_data;
-- What is the average quantity purchased per transaction?
SELECT 
	ROUND(AVG(quantity),2) AS average_order_value
FROM clean_cafe_sales_data;